-- ----------------------------
-- Table structure for s_user
-- ----------------------------
DROP TABLE IF EXISTS "public"."s_user";
CREATE TABLE "public"."s_user" (
  "id" uuid NOT NULL,
  "email" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "password" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "first_name" varchar(100) COLLATE "pg_catalog"."default",
  "last_name" varchar(100) COLLATE "pg_catalog"."default",
  "phone" varchar(20) COLLATE "pg_catalog"."default",
  "gender" varchar(10) COLLATE "pg_catalog"."default",
  "country" varchar(50) COLLATE "pg_catalog"."default",
  "enabled" bool NOT NULL DEFAULT true,
  "activated" bool NOT NULL DEFAULT false,
  "activate_token" varchar(64) COLLATE "pg_catalog"."default",
  "reset_token" varchar(64) COLLATE "pg_catalog"."default",
  "reset_token_expire_time" timestamp(6),
  "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp(6),
  "last_login_time" timestamp(6)
)
;

-- ----------------------------
-- Records of s_user  默认用户名：system@test.com 密码：123456
-- ----------------------------
INSERT INTO "public"."s_user" VALUES ('93c317a0-28ea-42a3-b875-a0603a01f2b9', 'system@test.com', '$2a$10$.jn8reapwe5k4bKbk32s9uBfDutGlP7/itN4R/N34WtUOS876g/mW', 'test', 'com', '121793424', NULL, NULL, 't', 't', '7c7d45f5f35243f6a0785a12ae05d627', NULL, NULL, '2026-07-30 19:23:57.251086', '2026-07-31 15:49:04.839412', '2026-07-31 15:49:04.837076');

-- ----------------------------
-- Uniques structure for table s_user
-- ----------------------------
ALTER TABLE "public"."s_user" ADD CONSTRAINT "s_user_email_key" UNIQUE ("email");
ALTER TABLE "public"."s_user" ADD CONSTRAINT "s_user_activate_token_key" UNIQUE ("activate_token");
ALTER TABLE "public"."s_user" ADD CONSTRAINT "s_user_reset_token_key" UNIQUE ("reset_token");

-- ----------------------------
-- Primary Key structure for table s_user
-- ----------------------------
ALTER TABLE "public"."s_user" ADD CONSTRAINT "s_user_pkey" PRIMARY KEY ("id");


-- ----------------------------
-- Table structure for chat_message
-- ----------------------------
DROP TABLE IF EXISTS "public"."chat_message";
CREATE TABLE "public"."chat_message" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "conversation_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
  "message_index" int4 NOT NULL,
  "message_type" varchar(20) COLLATE "pg_catalog"."default" NOT NULL,
  "message_content" text COLLATE "pg_catalog"."default" NOT NULL,
  "metadata" jsonb,
  "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
)
;
COMMENT ON COLUMN "public"."chat_message"."id" IS '数据id';
COMMENT ON COLUMN "public"."chat_message"."conversation_id" IS '会话id';
COMMENT ON COLUMN "public"."chat_message"."message_index" IS '消息序号（从0开始递增）';
COMMENT ON COLUMN "public"."chat_message"."message_type" IS '消息类型：USER/ASSISTANT/SYSTEM/TOOL';
COMMENT ON COLUMN "public"."chat_message"."message_content" IS '消息内容';
COMMENT ON COLUMN "public"."chat_message"."metadata" IS '消息元数据（JSON格式）';
COMMENT ON COLUMN "public"."chat_message"."create_time" IS '创建时间';
COMMENT ON TABLE "public"."chat_message" IS '对话消息记录';

-- ----------------------------
-- Indexes structure for table chat_message
-- ----------------------------
CREATE INDEX "idx_chat_message_conv_id" ON "public"."chat_message" USING btree (
  "conversation_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_chat_message_conv_id_idx" ON "public"."chat_message" USING btree (
  "conversation_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "message_index" "pg_catalog"."int4_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table chat_message
-- ----------------------------
ALTER TABLE "public"."chat_message" ADD CONSTRAINT "chat_message_pkey" PRIMARY KEY ("id");


-- ----------------------------
-- Table structure for chat_session
-- ----------------------------
DROP TABLE IF EXISTS "public"."chat_session";
CREATE TABLE "public"."chat_session" (
  "session_id" varchar(32) COLLATE "pg_catalog"."default" NOT NULL,
  "title" varchar(100) COLLATE "pg_catalog"."default",
  "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "user_id" uuid,
  "id" uuid NOT NULL
)
;
COMMENT ON COLUMN "public"."chat_session"."session_id" IS '会话id';
COMMENT ON COLUMN "public"."chat_session"."title" IS '会话标题';
COMMENT ON COLUMN "public"."chat_session"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."chat_session"."update_time" IS '更新时间';
COMMENT ON COLUMN "public"."chat_session"."user_id" IS '用户id';
COMMENT ON TABLE "public"."chat_session" IS '对话session';

-- ----------------------------
-- Indexes structure for table chat_session
-- ----------------------------
CREATE INDEX "session_id_index" ON "public"."chat_session" USING btree (
  "session_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "update_time_index" ON "public"."chat_session" USING btree (
  "update_time" "pg_catalog"."timestamp_ops" ASC NULLS LAST
);


-- ----------------------------
-- Table structure for device_base_info
-- ----------------------------
DROP TABLE IF EXISTS "public"."device_base_info";
CREATE TABLE "public"."device_base_info" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "device_name" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "device_model" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "device_type" varchar(20) COLLATE "pg_catalog"."default" NOT NULL,
  "category" varchar(100) COLLATE "pg_catalog"."default",
  "brand" varchar(50) COLLATE "pg_catalog"."default" DEFAULT 'MTN'::character varying,
  "price" numeric(12,2),
  "detail" text COLLATE "pg_catalog"."default",
  "core" text COLLATE "pg_catalog"."default",
  "specs" jsonb,
  "suitable_scenarios" text COLLATE "pg_catalog"."default",
  "product_url" varchar(500) COLLATE "pg_catalog"."default",
  "is_recommended" bool NOT NULL DEFAULT true,
  "sort_order" int4 DEFAULT 0,
  "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "creater" int8 NOT NULL DEFAULT 1,
  "updater" int8 NOT NULL DEFAULT 1
)
;
COMMENT ON COLUMN "public"."device_base_info"."id" IS '主键ID';
COMMENT ON COLUMN "public"."device_base_info"."device_name" IS '设备名称';
COMMENT ON COLUMN "public"."device_base_info"."device_model" IS '设备型号';
COMMENT ON COLUMN "public"."device_base_info"."device_type" IS '设备类型: ROUTER/SWITCH/REPEATER';
COMMENT ON COLUMN "public"."device_base_info"."category" IS '产品分类';
COMMENT ON COLUMN "public"."device_base_info"."brand" IS '品牌';
COMMENT ON COLUMN "public"."device_base_info"."price" IS '价格(元)';
COMMENT ON COLUMN "public"."device_base_info"."detail" IS '产品描述';
COMMENT ON COLUMN "public"."device_base_info"."core" IS '核心功能';
COMMENT ON COLUMN "public"."device_base_info"."specs" IS '规格参数(JSON)';
COMMENT ON COLUMN "public"."device_base_info"."suitable_scenarios" IS '适用场景';
COMMENT ON COLUMN "public"."device_base_info"."product_url" IS '官网产品详情页链接';
COMMENT ON COLUMN "public"."device_base_info"."is_recommended" IS '是否推荐';
COMMENT ON COLUMN "public"."device_base_info"."sort_order" IS '排序';
COMMENT ON COLUMN "public"."device_base_info"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."device_base_info"."update_time" IS '更新时间';
COMMENT ON COLUMN "public"."device_base_info"."creater" IS '创建人';
COMMENT ON COLUMN "public"."device_base_info"."updater" IS '更新人';
COMMENT ON TABLE "public"."device_base_info" IS '设备基础信息表';


-- ----------------------------
-- Table structure for web_function
-- ----------------------------
DROP TABLE IF EXISTS "public"."web_function";
CREATE TABLE "public"."web_function" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "function_code" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "function_name" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "module" varchar(100) COLLATE "pg_catalog"."default",
  "function_path" varchar(500) COLLATE "pg_catalog"."default",
  "open_url" varchar(500) COLLATE "pg_catalog"."default",
  "base_url" varchar(500) COLLATE "pg_catalog"."default",
  "description" text COLLATE "pg_catalog"."default",
  "config_method" text COLLATE "pg_catalog"."default",
  "config_steps" text COLLATE "pg_catalog"."default",
  "precautions" text COLLATE "pg_catalog"."default",
  "suitable_devices" text COLLATE "pg_catalog"."default",
  "icon" varchar(200) COLLATE "pg_catalog"."default",
  "button_text" varchar(100) COLLATE "pg_catalog"."default" DEFAULT '打开',
  "card_type" varchar(50) COLLATE "pg_catalog"."default" DEFAULT 'WEB_FUNCTION',
  "is_enabled" bool NOT NULL DEFAULT true,
  "sort_order" int4 DEFAULT 0,
  "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
)
;
COMMENT ON COLUMN "public"."web_function"."id" IS '主键ID';
COMMENT ON COLUMN "public"."web_function"."function_code" IS '功能编码（唯一）';
COMMENT ON COLUMN "public"."web_function"."function_name" IS '功能名称（前端展示）';
COMMENT ON COLUMN "public"."web_function"."module" IS '所属模块（如：路由交换、无线、安全、运维等）';
COMMENT ON COLUMN "public"."web_function"."function_path" IS '网页根路径（相对路径，如 /macc/device-password）';
COMMENT ON COLUMN "public"."web_function"."open_url" IS '完整打开URL（优先使用）';
COMMENT ON COLUMN "public"."web_function"."base_url" IS '域名基础路径';
COMMENT ON COLUMN "public"."web_function"."description" IS '功能描述（一句话简介）';
COMMENT ON COLUMN "public"."web_function"."config_method" IS '具体配置方式（Markdown/HTML 文本）';
COMMENT ON COLUMN "public"."web_function"."config_steps" IS '配置步骤（JSON 数组字符串）';
COMMENT ON COLUMN "public"."web_function"."precautions" IS '注意事项';
COMMENT ON COLUMN "public"."web_function"."suitable_devices" IS '适用设备';
COMMENT ON COLUMN "public"."web_function"."icon" IS '图标';
COMMENT ON COLUMN "public"."web_function"."button_text" IS '按钮文案';
COMMENT ON COLUMN "public"."web_function"."card_type" IS '卡片类型（前端识别渲染样式）';
COMMENT ON COLUMN "public"."web_function"."is_enabled" IS '是否启用';
COMMENT ON COLUMN "public"."web_function"."sort_order" IS '排序权重';
COMMENT ON COLUMN "public"."web_function"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."web_function"."update_time" IS '更新时间';
COMMENT ON TABLE "public"."web_function" IS '网页功能打开配置表（AI一键打开网页）';

ALTER TABLE "public"."web_function" ADD CONSTRAINT "web_function_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."web_function" ADD CONSTRAINT "web_function_code_key" UNIQUE ("function_code");

CREATE INDEX "idx_web_function_enabled_sort" ON "public"."web_function" USING btree (
  "is_enabled" "pg_catalog"."bool_ops" ASC NULLS LAST,
  "sort_order" "pg_catalog"."int4_ops" ASC NULLS LAST
);

-- ----------------------------
-- Records of web_function — 示例数据
-- ----------------------------
INSERT INTO "public"."web_function" ("function_code","function_name","module","function_path","base_url","description","config_method","precautions","suitable_devices","icon","button_text","card_type","is_enabled","sort_order") VALUES
('version_notes','版本说明','平台信息','/version-notes',NULL,'查看平台各版本更新日志、新增功能、优化项及问题修复记录，帮助您快速了解产品演进与最新特性。',
NULL,'版本说明页面仅展示平台已正式发布的版本信息，灰度或内测版本可能不在其中。',NULL,'icon-version','打开','WEB_FUNCTION','t',1);

-- ----------------------------
-- Table structure for version_record
-- ----------------------------
DROP TABLE IF EXISTS "public"."version_record";
CREATE TABLE "public"."version_record" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "release_date" date NOT NULL,
  "title" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "version" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "content" jsonb,
  "sort_order" int4 DEFAULT 0,
  "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
)
;
COMMENT ON COLUMN "public"."version_record"."id" IS '主键ID';
COMMENT ON COLUMN "public"."version_record"."release_date" IS '版本发布日期';
COMMENT ON COLUMN "public"."version_record"."title" IS '版本标题';
COMMENT ON COLUMN "public"."version_record"."version" IS '版本号';
COMMENT ON COLUMN "public"."version_record"."content" IS '更新内容（JSON数组：按新增功能/优化功能/bugfix等分类）';
COMMENT ON COLUMN "public"."version_record"."sort_order" IS '排序权重';
COMMENT ON COLUMN "public"."version_record"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."version_record"."update_time" IS '更新时间';
COMMENT ON TABLE "public"."version_record" IS '版本更新记录表';

ALTER TABLE "public"."version_record" ADD CONSTRAINT "version_record_pkey" PRIMARY KEY ("id");

CREATE INDEX "idx_version_record_release_date" ON "public"."version_record" USING btree (
  "release_date" "pg_catalog"."date_ops" DESC NULLS LAST
);

-- ----------------------------
-- Records of version_record
-- ----------------------------
INSERT INTO "public"."version_record" ("release_date","title","version","content","sort_order") VALUES
('2026-07-26','2026-07-26 AI Agent v1.0.0 更新说明','v1.0.0','[{"type":"基础功能","items":["基础推荐功能"]}]'::jsonb, 1),
('2026-08-01','2026-08-01 AI Agent v1.0.1 更新说明','v1.0.1','[{"type":"新增功能","items":["历史用户对话数据搜索","AI一键打开功能"]},{"type":"bugfix","items":["修复后台重复保存用户对话消息的问题"]}]'::jsonb, 2);
