-- ----------------------------
-- Table structure for s_user
-- ----------------------------
DROP TABLE IF EXISTS "public"."s_user";
CREATE TABLE "public"."s_user" (
  "id" uuid NOT NULL,
  "email" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "password" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "first_name" varchar(100) COLLATE "pg_catalog"."default",
  "last_name" varchar(100) COLLATE "pg_catalog"."default",
  "phone" varchar(20) COLLATE "pg_catalog"."default",
  "gender" varchar(10) COLLATE "pg_catalog"."default",
  "country" varchar(50) COLLATE "pg_catalog"."default",
  "enabled" bool NOT NULL DEFAULT true,
  "activated" bool NOT NULL DEFAULT false,
  "activate_token" varchar(64) COLLATE "pg_catalog"."default",
  "reset_token" varchar(64) COLLATE "pg_catalog"."default",
  "reset_token_expire_time" timestamp(6),
  "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp(6),
  "last_login_time" timestamp(6)
)
;

-- ----------------------------
-- Records of s_user  默认用户名：system@test.com 密码：123456
-- ----------------------------
INSERT INTO "public"."s_user" VALUES ('93c317a0-28ea-42a3-b875-a0603a01f2b9', 'system@test.com', '$2a$10$.jn8reapwe5k4bKbk32s9uBfDutGlP7/itN4R/N34WtUOS876g/mW', 'test', 'com', '121793424', NULL, NULL, 't', 't', '7c7d45f5f35243f6a0785a12ae05d627', NULL, NULL, '2026-07-30 19:23:57.251086', '2026-07-31 15:49:04.839412', '2026-07-31 15:49:04.837076');

-- ----------------------------
-- Uniques structure for table s_user
-- ----------------------------
ALTER TABLE "public"."s_user" ADD CONSTRAINT "s_user_email_key" UNIQUE ("email");
ALTER TABLE "public"."s_user" ADD CONSTRAINT "s_user_activate_token_key" UNIQUE ("activate_token");
ALTER TABLE "public"."s_user" ADD CONSTRAINT "s_user_reset_token_key" UNIQUE ("reset_token");

-- ----------------------------
-- Primary Key structure for table s_user
-- ----------------------------
ALTER TABLE "public"."s_user" ADD CONSTRAINT "s_user_pkey" PRIMARY KEY ("id");


-- ----------------------------
-- Table structure for chat_message
-- ----------------------------
DROP TABLE IF EXISTS "public"."chat_message";
CREATE TABLE "public"."chat_message" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "conversation_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
  "message_index" int4 NOT NULL,
  "message_type" varchar(20) COLLATE "pg_catalog"."default" NOT NULL,
  "message_content" text COLLATE "pg_catalog"."default" NOT NULL,
  "metadata" jsonb,
  "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
)
;
COMMENT ON COLUMN "public"."chat_message"."id" IS '数据id';
COMMENT ON COLUMN "public"."chat_message"."conversation_id" IS '会话id';
COMMENT ON COLUMN "public"."chat_message"."message_index" IS '消息序号（从0开始递增）';
COMMENT ON COLUMN "public"."chat_message"."message_type" IS '消息类型：USER/ASSISTANT/SYSTEM/TOOL';
COMMENT ON COLUMN "public"."chat_message"."message_content" IS '消息内容';
COMMENT ON COLUMN "public"."chat_message"."metadata" IS '消息元数据（JSON格式）';
COMMENT ON COLUMN "public"."chat_message"."create_time" IS '创建时间';
COMMENT ON TABLE "public"."chat_message" IS '对话消息记录';

-- ----------------------------
-- Indexes structure for table chat_message
-- ----------------------------
CREATE INDEX "idx_chat_message_conv_id" ON "public"."chat_message" USING btree (
  "conversation_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_chat_message_conv_id_idx" ON "public"."chat_message" USING btree (
  "conversation_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "message_index" "pg_catalog"."int4_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table chat_message
-- ----------------------------
ALTER TABLE "public"."chat_message" ADD CONSTRAINT "chat_message_pkey" PRIMARY KEY ("id");


-- ----------------------------
-- Table structure for chat_session
-- ----------------------------
DROP TABLE IF EXISTS "public"."chat_session";
CREATE TABLE "public"."chat_session" (
  "session_id" varchar(32) COLLATE "pg_catalog"."default" NOT NULL,
  "title" varchar(100) COLLATE "pg_catalog"."default",
  "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "user_id" uuid,
  "id" uuid NOT NULL
)
;
COMMENT ON COLUMN "public"."chat_session"."session_id" IS '会话id';
COMMENT ON COLUMN "public"."chat_session"."title" IS '会话标题';
COMMENT ON COLUMN "public"."chat_session"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."chat_session"."update_time" IS '更新时间';
COMMENT ON COLUMN "public"."chat_session"."user_id" IS '用户id';
COMMENT ON TABLE "public"."chat_session" IS '对话session';

-- ----------------------------
-- Indexes structure for table chat_session
-- ----------------------------
CREATE INDEX "session_id_index" ON "public"."chat_session" USING btree (
  "session_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "update_time_index" ON "public"."chat_session" USING btree (
  "update_time" "pg_catalog"."timestamp_ops" ASC NULLS LAST
);


-- ----------------------------
-- Table structure for device_base_info
-- ----------------------------
DROP TABLE IF EXISTS "public"."device_base_info";
CREATE TABLE "public"."device_base_info" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "device_name" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "device_model" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "device_type" varchar(20) COLLATE "pg_catalog"."default" NOT NULL,
  "category" varchar(100) COLLATE "pg_catalog"."default",
  "brand" varchar(50) COLLATE "pg_catalog"."default" DEFAULT 'MTN'::character varying,
  "price" numeric(12,2),
  "detail" text COLLATE "pg_catalog"."default",
  "core" text COLLATE "pg_catalog"."default",
  "specs" jsonb,
  "suitable_scenarios" text COLLATE "pg_catalog"."default",
  "product_url" varchar(500) COLLATE "pg_catalog"."default",
  "is_recommended" bool NOT NULL DEFAULT true,
  "sort_order" int4 DEFAULT 0,
  "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "creater" int8 NOT NULL DEFAULT 1,
  "updater" int8 NOT NULL DEFAULT 1
)
;
COMMENT ON COLUMN "public"."device_base_info"."id" IS '主键ID';
COMMENT ON COLUMN "public"."device_base_info"."device_name" IS '设备名称';
COMMENT ON COLUMN "public"."device_base_info"."device_model" IS '设备型号';
COMMENT ON COLUMN "public"."device_base_info"."device_type" IS '设备类型: ROUTER/SWITCH/REPEATER';
COMMENT ON COLUMN "public"."device_base_info"."category" IS '产品分类';
COMMENT ON COLUMN "public"."device_base_info"."brand" IS '品牌';
COMMENT ON COLUMN "public"."device_base_info"."price" IS '价格(元)';
COMMENT ON COLUMN "public"."device_base_info"."detail" IS '产品描述';
COMMENT ON COLUMN "public"."device_base_info"."core" IS '核心功能';
COMMENT ON COLUMN "public"."device_base_info"."specs" IS '规格参数(JSON)';
COMMENT ON COLUMN "public"."device_base_info"."suitable_scenarios" IS '适用场景';
COMMENT ON COLUMN "public"."device_base_info"."product_url" IS '官网产品详情页链接';
COMMENT ON COLUMN "public"."device_base_info"."is_recommended" IS '是否推荐';
COMMENT ON COLUMN "public"."device_base_info"."sort_order" IS '排序';
COMMENT ON COLUMN "public"."device_base_info"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."device_base_info"."update_time" IS '更新时间';
COMMENT ON COLUMN "public"."device_base_info"."creater" IS '创建人';
COMMENT ON COLUMN "public"."device_base_info"."updater" IS '更新人';
COMMENT ON TABLE "public"."device_base_info" IS '设备基础信息表';
